api_version: 1
runtime: python
environment: development
debug: True
testing: True
secret_key: None
token: None
runtime_config:
  python_version: 3

logging:
    version: 1
    formatters:
      default:
        format: '%(asctime)s %(levelname)s: %(filename)s %(funcName)s:%(lineno)d : %(message)s'
    handlers:
      wsgi:
        class: logging.StreamHandler
        stream: 'ext://flask.logging.wsgi_errors_stream'
        formatter: default
    root:
      level: INFO
      handlers:
        - wsgi

